<?php
/**
 * Description of Yield
 *
 * @author Victor Angelier
 * @copyright (c) 2012, Wielink Websolutions BV te Nunspeet
 * @package BCI - Beheer Collectieve Inkomensverzekeringen
 * @subpackage Application source
 */

/**
 * '{yield}' will be replaced with all output generated by the controller/view.
 */
class Yield 
{	
	/**
	 * Create a layout/template
	 * @global type $OUT
	 */
    public function doYield()
    {         
        global $OUT;
		$default = APPPATH.'views/layouts/default.php';

        $CI =& get_instance();
		
        $view = $output = $CI->output->get_output();	
        $layout = (isset($CI->layout))?$CI->layout:'default';

        if ($layout !== false){
            
			$layout .= (!preg_match('/(.+).php$/', $layout))?'.php':'';
            $requested = APPPATH.'views/layouts/' . $layout;
			
            if (file_exists($requested)){
                $layout_output = $CI->load->file($requested, true);
                $view = str_replace("{yield}", $output, $layout_output);
            }else{
                $layout_output = $CI->load->file($default, true);
                $view = str_replace("{yield}", $output, $layout_output);
			}
        }

        $OUT->_display($view);
    }
}
?>
